# Generated by Django 4.0.5 on 2022-06-25 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty_username', models.CharField(max_length=100, unique=True)),
                ('faculty_password', models.CharField(max_length=50)),
                ('faculty_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_taken', models.IntegerField()),
                ('PPE_in_1_marks', models.IntegerField()),
                ('PPE_in_2_marks', models.IntegerField()),
                ('PPE_in_3_marks', models.IntegerField()),
                ('PPE_in_4_marks', models.IntegerField()),
                ('PPE_in_5_marks', models.IntegerField()),
                ('End_exam_marks', models.IntegerField()),
                ('course_teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.faculty')),
                ('s_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.courses')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hrs_1_2', models.BooleanField(default=False)),
                ('hrs_3_4', models.BooleanField(default=False)),
                ('hrs_5_6', models.BooleanField(default=False)),
                ('hrs_7_8', models.BooleanField(default=False)),
                ('s_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.courses')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.courses')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluppapp.faculty')),
            ],
        ),
    ]
