# Generated by Django 4.0.2 on 2022-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0004_facultycourses_f_section_studentcourses_s_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='course_taken',
        ),
        migrations.AddField(
            model_name='facultycourses',
            name='course_sem',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='facultycourses',
            name='course_year',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='course_sem',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='course_year',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
