# Generated by Django 4.0.2 on 2022-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0005_remove_studentcourses_course_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
