# Generated by Django 4.0.2 on 2022-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0007_facultycourses_f_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='End_exam_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='PPE_in_1_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='PPE_in_2_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='PPE_in_3_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='PPE_in_4_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='PPE_in_5_marks',
            field=models.IntegerField(default=None),
        ),
    ]
