# Generated by Django 4.0.2 on 2022-06-26 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0009_alter_studentcourses_end_exam_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendace',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
