# Generated by Django 4.0.2 on 2022-06-26 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0010_alter_studentattendace_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendace',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
