# Generated by Django 4.0.2 on 2022-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0011_alter_studentattendace_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_1_2',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_3_4',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_5_6',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_7_8',
            field=models.CharField(default='F', max_length=5),
        ),
    ]
