# Generated by Django 4.0.2 on 2022-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluppapp', '0012_alter_studentattendace_hrs_1_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_1_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_3_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_5_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentattendace',
            name='hrs_7_8',
            field=models.BooleanField(default=False),
        ),
    ]
